services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd"
      MSSQL_PID: "Developer"
      TZ: Asia/Jakarta
      PGTZ: Asia/Jakarta
    ports:
      - "1433:1433"
    volumes:
      - /home/$USER/volumes/sqlserver-data:/var/opt/mssql

#Jika menggunakan navicat sebagai tools bisa pakai odbc 
# https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver17