services:
  postgres17:
    image: postgres:17.5-bookworm
    container_name: postgres17
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Jakarta
      PGTZ: Asia/Jakarta
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=256MB
      -c work_mem=16MB
      -c maintenance_work_mem=128MB
      -c timezone=Asia/Jakarta
      -c log_timezone=Asia/Jakarta
    volumes:
      - ~/volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
